libxode_lib = static_library('xode',
  [
    'xstream.c', 'expat.c', 'xhash.c', 'genhash.c', 'hashtable.c',
    'pool.c', 'sha.c', 'snprintf.c', 'socket.c', 'str.c',
    'xmlnode.c', 'xmlparse.c', 'xmlrole.c', 'xmltok.c',
  ],
  include_directories: include_directories('include'),
  dependencies: [glib_dep],
)
